module:
   imports:
      - path: github.com/eens1/config

languageName: "Français"
defaultContentLanguage: fr
params:
   dateFormat: "Jan 02, 2006"
   featuredPosts:
     - /spiritualite/rosaire
     - /catechisme
     - /doctrine/croyances-necessaires
     - /apologetique/hors-de-l-eglise-pas-de-salut
   sidebar:
     - title: "Accueil"
       link: "/"
     - title: "Bible"
       link: "/bible"
     - title: "Doctrine"
       link: "/doctrine"
     - title: "Apologétique"
       link: "/apologetique"
     - title: "Spiritualité"
       link: "/spiritualite"
     - title: "Livres"
       link: "/livres"
     - title: "À propos"
       link: "/a-propos"
     - title: "Autres langues"
       submenu:
         - title: "English"
           link: "https://eens-en.netlify.app"
         - title: "Italiano"
           link: "https://eens-it.netlify.app"
     - title: "Contact"
       link: "/contact"
     - title: "Liens"
       submenu:
         - title: "VaticanCatholic.com"
           link: "https://vaticancatholic.com"
         - title: "VaticanCatholique.com"
           link: "https://vaticancatholique.com"
         - title: "VaticanoCattolico.com"
           link: "https://vaticanocattolico.com"
