baseURL: "https://eens-fr.netlify.app"
title: "Extra Ecclesiam Nulla Salus"

module:
   imports:
      - path: github.com/eens1/config

languageName: "Français"
defaultContentLanguage: fr

params:
   dateFormat: "Jan 02, 2006"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false
menu:
   main:
      - name: Accueil
        url: /
        weight: 1

      - name: Contact
        url: /contact
        weight: 2

      - name: "À propos"
        url: /a-propos
        weight: 3 

      - name: "English"
        url: "https://eens-en.netlify.app"
        weight: 4 
        params:
          target: "_blank"

      - name: "Italiano"
        url: "https://eens-it.netlify.app"
        weight: 5 
        params:
          target: "_blank"

      - identifier: youtube
        name: ""
        url: "https://www.youtube.com/@BroMatthewCap"
        weight: 6
        pre: "<i class='fab fa-youtube'></i> "
        params:
          target: "_blank"

      - identifier: twitter
        name: ""
        url: "https://x.com/BroMatthewOFMC"
        weight: 7
        pre: '<i class="fab fa-x-twitter"></i>'
        params:
          target: "_blank"

      - identifier: theme-switcher
        name: ""
        url: "#"
        weight: 8
        pre: '<i id="theme-icon" class="fas fa-moon"></i>'

