baseURL: "https://eens-fr.netlify.app"
title: "Extra Ecclesiam Nulla Salus"

module:
   imports:
      - path: github.com/eens1/config

languageName: "Français"
defaultContentLanguage: fr

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false
menu:
   main:
      - name: Accueil
        url: /
        weight: 1

      - name: Contact
        url: /contact
        weight: 2

      - name: "À propos"
        url: /a-propos
        weight: 3 

      - name: "English"
        url: "https://eens-en.netlify.app"
        weight: 4 
        params:
          target: "_blank"

      - name: "Italiano"
        url: "https://eens-it.netlify.app"
        weight: 5 
        params:
          target: "_blank"

      - identifier: youtube
        name: ""
        url: "https://www.youtube.com/@BroMatthewCap"
        weight: 6
        pre: "<i class='fab fa-youtube'></i> "
        params:
          target: "_blank"

      - identifier: twitter
        name: ""
        url: "https://x.com/BroMatthewOFMC"
        weight: 7
        pre: '<i class="fab fa-x-twitter"></i>'
        params:
          target: "_blank"

      - identifier: theme-switcher
        name: ""
        url: "#"
        weight: 8
        pre: '<i id="theme-icon" class="fas fa-moon"></i>'

params:
   dateFormat: "Jan 02, 2006"
   featured_boxes:
      - icon: "icons/bible"
        title: "La Bible prouve le catholicisme"
        description: "La Bible prouve les enseignements de l'Église catholique."
        link: "/apologetique/bible-prouve-catholicisme/"
      - icon: "icons/church"
        title: "Hors de l'Église pas de salut"
        description: "Défense de ce dogme fondamental du Christianisme, malheureusement rejeté par presque tout ceux qui prétendent être catholique aujourd'hui."
        link: "/apologetique/hors-de-l-eglise-pas-de-salut/"
      - icon: "icons/open-book"
        title: "Catéchisme"
        description: "Grand catéchisme de Saint Pierre Canisius. Précis de la doctrine chrétienne."
        link: "/catechisme"
      - icon: "icons/colosseum"
        title: "Vatican II démasqué"
        description: "Vatican II ne représente pas l'Église catholique mais une secte qui enseigne un faux-évangile."
        link: "/apologetique/contre-vatican-ii"
      - icon: "icons/pray"
        title: "Prière du saint Rosaire"
        description: "Une dévotion très importante à la Très Sainte Vierge Marie."
        link: "/spiritualite/rosaire"
      - icon: "icons/cross"
        title: "Conversion à la foi catholique"
        description: "Étapes complètes de conversion à la foi catholique traditionnelle nécessaire au salut."
        link: "/spiritualite/etapes-de-conversion"
      - icon: "icons/play"
        title: "Vidéos"
        description: ""
        link: "/videos"
      - icon: "icons/internet-access"
        title: "Liens"
        description: "Liens vers des sites catholiques."
        link: "/liens"

   quickLinks:
      group1:
         title: "Bible"
         order: 1
         url: "/bible"
         links:
            - title: "Bible Glaire"
              url: "/bible/glaire"
            - title: "Biblia Vulgata"
              url: "/bible/vulgata"
      group2:
         title: "Doctrine"
         order: 2
         url: "/doctrine"
         links:
            - title: "Croyances nécessaire au salut"
              url: "/doctrine/croyances-necessaires"
            - title: "Commandements"
              url: "/doctrine/commandements"
            - title: "Baptême"
              url: "/doctrine/bapteme"
            - title: "Confession"
              url: "/doctrine/confession"
            - title: "Glossaire"
              url: "/doctrine/glossaire"
      group3:
         title: "Apologétique"
         order: 3
         url: "/apologetique"
         links:
            - title: "Bible prouve le catholicisme"
              url: "/apologetique/bible-prouve-catholicisme"
            - title: "Hors de l'Église pas de salut"
              url: "/apologetique/hors-de-l-eglise-pas-de-salut"
            - title: "Divinité de Jésus-Christ"
              url: "/apologetique/divinite-du-christ/"
            - title: "Secte Vatican II"
              url: "/apologetique/vatican-ii"
      group4:
         title: "Spiritualité"
         order: 4
         url: "/spiritualite"
         links:
            - title: "Étapes de conversion"
              url: "/spiritualite/etapes-de-conversion"
            - title: "Rosaire"
              url: "/spiritualite/rosaire"
            - title: "Sacrements"
              url: "/spiritualite/sacrements"
            - title: "Directeur des consciences"
              url: "/spiritualite/jean-francois-de-reims"
            - title: "Glossaire"
              url: "/spiritualite/glossaire"
            - title: "Prières"
              url: "/spiritualite/prieres"
            - title: "Livres"
              url: "/livres"
      group5:
         title: "Vie religieuse"
         order: 5
         url: "/vie-religieuse"
         links:
            - title: "Frères Mineurs"
              url: "/vie-religieuse/freres-mineurs"
            - title: "Carmel"
              url: "/vie-religieuse/carmel"
            - title: "Glossaire"
              url: "/vie-religieuse/glossaire"
            - title: "Concile de Trente"
              url: "/vie-religieuse/concile-de-trente"
            - title: "Droit canonique"
              url: "/vie-religieuse/droit-canonique"

   homepage_sections:
     - id: "section1"
       headline: "Hors de l'Église pas de salut"
       description: "Défense de ce dogme fondamental du Christianisme."
       button_text: "Explorer"
       url: "/apologetique/hors-de-l-eglise-pas-de-salut"
       posts:
         - "blog/hors-de-l-eglise-pas-de-salut-bible"
         - "blog/hors-de-l-eglise-pas-de-salut-bible"
         - "blog/hors-de-l-eglise-pas-de-salut-bible"
         - "blog/hors-de-l-eglise-pas-de-salut-bible"
