module:
   imports:
      - path: github.com/eens1/config

languageName: "Français"
defaultContentLanguage: fr
params:
   dateFormat: "Jan 02, 2006"
menu:
   main:
      - identifier: home
        url: /
        weight: 1
        pre: <i class="fas fa-home"></i>

      - name: Bible
        url: /bible
        weight: 2

      - name: Doctrine
        url: /doctrine
        weight: 3

      - name: Spirtualité
        url: /spiritualite
        weight: 4
 
      - identifier: apologetique
        name: Apologétique
        url: /apologetique
        weight: 5
 
      - url: /contact
        name: Contact
        weight: 6
      
      - identifier: lang
        weight: 7
        name: "LANG"
        pre: "<i class='fas fa-globe'></i>"

      - url: 'https://eens-en.netlify.app'
        name: English
        parent: lang

      - url: 'https://eens-it.netlify.app'
        name: Italiano 
        parent: lang

params:
  featuredPosts:
    - /spiritualite/rosaire
    - /catechisme
    - /doctrine/croyances-necessaires
    - /apologetique/hors-de-l-eglise-pas-de-salut
