baseURL: https://eens-fr.netlify.app
title: "Extra Ecclesia Nulla Salus"

module:
   imports:
      - path: github.com/eens1/config

languageName: "Français"
defaultContentLanguage: fr
params:
   dateFormat: "Jan 02, 2006"
menu:
   main:
      - name: Accueil
        url: /
        weight: 1

      - name: Contact
        url: /contact
        weight: 2

      - name: "À propos"
        url: /a-propos
        weight: 3 

      - name: "English"
        url: "https://eens-en.netlify.app"
        weight: 4 

      - name: "Italiano"
        url: "https://eens-it.netlify.app"
        weight: 5 

params:
   featuredPosts:
     - /spiritualite/rosaire
     - /catechisme
     - /doctrine/croyances-necessaires
     - /apologetique/hors-de-l-eglise-pas-de-salut
   sidebar:
     - title: "Accueil"
       link: "/"
     - title: "À propos"
       link: "/a-propos"
     - title: "Autres Langues"
       link: "/blog"
       submenu:
         - title: "English"
           link: "https://eens-en.netlify.app"
         - title: "Italiano"
           link: "https://eens-it.netlify.app"
     - title: "Contact"
       link: "/contact"
